- hosts: test
  become: yes
  become_user: ubuntu
  tasks:
    - name: Run kubernetes deployment command.
      command: kubectl apply --kubeconfig /home/ubuntu/kube.conf -f /home/ubuntu/deployment.yml
      args:
        chdir: /home/ubuntu
    - name: Sleep 10 seconds
      command:  sleep 10

    - name: Display deployment details.
      command: kubectl get deployments --kubeconfig /home/ubuntu/kube.conf
   
    - name: Display service details.
      command: kubectl get svc --kubeconfig /home/ubuntu/kube.conf
   
