apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31020
    targetPort: 8080
  selector:
    app: webapp
